### PR TITLE
Delay use of AddCronTrigger fields to prevent NPE

### LINKED ISSUE #86: `RecipeIntrospectionException`: Unable to call primary constructor for `AddCronTrigger`
As [reported through Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1689594146939979?thread_ts=1689589327.257089&cid=C01A843MWG5).

>  [WARNING] Unable to configure org.openrewrite.github.AddCronTrigger
org.openrewrite.config.RecipeIntrospectionException: Unable to call primary constructor for Recipe class org.openrewrite.github.AddCronTrigger

[AddCronTrigger has two constructors](https://github.com/openrewrite/rewrite-github-actions/blob/main/src/main/java/org/openrewrite/github/AddCronTrigger.java) currently.

### PR DESCRIPTION
**Pull request by timtebeek**
Fixes #86 
Fixes https://github.com/openrewrite/rewrite-spring/issues/391

### CODE REVIEW

File: src/test/java/org/openrewrite/github/AddCronTriggerTest.java [hunk 1]
```diff
@@ -176,4 +177,9 @@ void cronTriggerRandom(String cronExpression, String actualCronValue) {
           )
         );
     }
+
+    @Test
+    void constructRecipeWithRecipeIntrospectionUtilsShouldNotFail() {
+        RecipeIntrospectionUtils.constructRecipe(AddCronTrigger.class);
+    }
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/github/AddCronTriggerTest.java:184]: Maybe remove this test again following https://github.com/openrewrite/rewrite/pull/3420
```suggestion
```

File: src/test/java/org/openrewrite/github/AddCronTriggerTest.java [hunk 2]
```diff
@@ -21,6 +21,7 @@
 import org.junit.jupiter.params.provider.CsvSource;
 import org.junit.jupiter.params.provider.NullSource;
 import org.junit.jupiter.params.provider.ValueSource;
+import org.openrewrite.internal.RecipeIntrospectionUtils;
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/github/AddCronTriggerTest.java:24]:
```suggestion
```

File: src/test/java/org/openrewrite/github/AddCronTriggerTest.java (hunk 1 above)
Comment (joanvr) [reply src/test/java/org/openrewrite/github/AddCronTriggerTest.java:184]: yes, let's wait until we merge the extra check on rewriteRun, and then we will be able to get rid of all those "extra weird tests"
